glob.o: glob.cc ../stypes.h ../ddconfig.h ../custom.h
inst.o: inst.cc ../ddconfig.h ../custom.h z80cl.h ../sim.src/uccl.h \
  ../stypes.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h ../appcl.h ../optioncl.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h \
  ../gui.src/ifcl.h ../cmd.src/commandcl.h ../sim.src/memcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h \
  instcl.h z80mac.h
inst_cb.o: inst_cb.cc ../ddconfig.h ../custom.h z80cl.h ../sim.src/uccl.h \
  ../stypes.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h ../appcl.h ../optioncl.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h \
  ../gui.src/ifcl.h ../cmd.src/commandcl.h ../sim.src/memcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h \
  instcl.h z80mac.h
inst_dd.o: inst_dd.cc ../ddconfig.h ../custom.h z80cl.h ../sim.src/uccl.h \
  ../stypes.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h ../appcl.h ../optioncl.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h \
  ../gui.src/ifcl.h ../cmd.src/commandcl.h ../sim.src/memcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h \
  instcl.h z80mac.h inst_xd.cc
inst_ddcb.o: inst_ddcb.cc ../ddconfig.h ../custom.h z80cl.h \
  ../sim.src/uccl.h ../stypes.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h \
  ../appcl.h ../optioncl.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../gui.src/ifcl.h ../cmd.src/commandcl.h \
  ../sim.src/memcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h inst_xxcb.cc
inst_ed.o: inst_ed.cc ../ddconfig.h ../custom.h z80cl.h ../sim.src/uccl.h \
  ../stypes.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h ../appcl.h ../optioncl.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h \
  ../gui.src/ifcl.h ../cmd.src/commandcl.h ../sim.src/memcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h \
  instcl.h z80mac.h
inst_fd.o: inst_fd.cc ../ddconfig.h ../custom.h z80cl.h ../sim.src/uccl.h \
  ../stypes.h ../pobjcl.h ../pobjt.h ../eventcl.h ../sim.src/hwcl.h \
  ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h ../appcl.h ../optioncl.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../gui.src/guicl.h \
  ../gui.src/ifcl.h ../cmd.src/commandcl.h ../sim.src/memcl.h \
  ../errorcl.h ../sim.src/brkcl.h ../sim.src/stackcl.h regsz80.h \
  instcl.h z80mac.h inst_xd.cc
inst_fdcb.o: inst_fdcb.cc ../ddconfig.h ../custom.h z80cl.h \
  ../sim.src/uccl.h ../stypes.h ../pobjcl.h ../pobjt.h ../eventcl.h \
  ../sim.src/hwcl.h ../sim.src/guiobjcl.h ../cmd.src/newcmdcl.h \
  ../appcl.h ../optioncl.h ../sim.src/argcl.h ../sim.src/simcl.h \
  ../gui.src/guicl.h ../gui.src/ifcl.h ../cmd.src/commandcl.h \
  ../sim.src/memcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h regsz80.h instcl.h z80mac.h inst_xxcb.cc
inst_xd.o: inst_xd.cc
inst_xxcb.o: inst_xxcb.cc
simz80.o: simz80.cc simz80cl.h ../sim.src/simcl.h ../pobjcl.h \
  ../ddconfig.h ../custom.h ../pobjt.h ../eventcl.h \
  ../cmd.src/newcmdcl.h ../appcl.h ../optioncl.h ../stypes.h \
  ../sim.src/argcl.h ../cmd.src/commandcl.h ../gui.src/guicl.h \
  ../gui.src/ifcl.h ../sim.src/guiobjcl.h ../sim.src/uccl.h \
  ../sim.src/hwcl.h ../sim.src/memcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h z80cl.h regsz80.h instcl.h
sz80.o: sz80.cc ../globals.h ../ddconfig.h ../custom.h ../stypes.h \
  ../appcl.h ../pobjcl.h ../pobjt.h ../eventcl.h ../optioncl.h \
  ../sim.src/argcl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
  ../cmd.src/commandcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/memcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h simz80cl.h
z80.o: z80.cc ../ddconfig.h ../custom.h ../i_string.h ../pobjcl.h \
  ../pobjt.h ../eventcl.h ../sim.src/simcl.h ../cmd.src/newcmdcl.h \
  ../appcl.h ../optioncl.h ../stypes.h ../sim.src/argcl.h \
  ../cmd.src/commandcl.h ../gui.src/guicl.h ../gui.src/ifcl.h \
  ../sim.src/guiobjcl.h ../sim.src/uccl.h ../sim.src/hwcl.h \
  ../sim.src/memcl.h ../errorcl.h ../sim.src/brkcl.h \
  ../sim.src/stackcl.h z80cl.h regsz80.h instcl.h glob.h
